name: "Slidez"
description: "Configures Drupal to run a slide presentation"
type: "Site"

install:
  - view_transitions
  - slidez

config:
  actions:
    system.theme:
      simple_config_update:
        default: 'slidez'